# Generated by Django 5.1.4 on 2024-12-20 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_venue_match_stadium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='economic_seats',
        ),
        migrations.RemoveField(
            model_name='match',
            name='regular_seats',
        ),
        migrations.RemoveField(
            model_name='match',
            name='vip_seats',
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('spain_league', 'La Liga'), ('german_league', 'Bundesliga'), ('England_league', 'Premier League'), ('france_league', 'Ligue 1'), ('italy_league', 'Seria A'), ('champions_league', 'Champions League')], default='laliga', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='backend.match')),
            ],
        ),
    ]
