# Generated by Django 5.1.4 on 2024-12-20 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_match_league_cart_matchticket_order_cartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('original_url', models.URLField()),
            ],
        ),
    ]
