# Generated by Django 5.1.4 on 2024-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_cartitem_match_ticket_cartitem_cart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
