# Generated by Django 5.1.4 on 2024-12-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_shopitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(default='TEMP123456', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='backend.cartitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
